import localFont from "next/font/local";
import { Sour_Gummy, Acme } from "next/font/google"
import "./globals.css"

const sourGummy = Sour_Gummy({
  subsets: ["latin"],
  variable: "--font-sour-gummy",
  weight: ["400"],
})
const acme = Acme({
  subsets: ["latin"],
  variable: "--font-acme",
  weight: ["400"],
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}) {
  return (
    <html lang="en">
      <body className={`${sourGummy.variable} ${acme.variable} bg-neutral-100`}>
        {children}
      </body>
    </html>
  );
}