name: Deploy site

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  run-locally:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Start app
        run: |
          sudo systemctl restart mysite.service

